name: base_exapmle
description: "Base Project."

version: 1.0.0+1

environment:
  flutter: ^3.24.0
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: any # An exact version pin will be provided by the Flutter SDK
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  web_benchmarks: ^0.1.0
  
flutter:
  uses-material-design: true

 